'use client'

interface WatermarkProps {
  plan: 'free' | 'pro'
}

/**
 * Renders a branded watermark at the bottom of analysis output sections.
 * Only visible for free-tier users; returns null for pro-tier.
 */
export function Watermark({ plan }: WatermarkProps): JSX.Element | null {
  if (plan === 'pro') {
    return null
  }

  return (
    <p className="mt-4 text-center text-xs text-gray-400 opacity-60 select-none">
      Generated by StoryForge.id — Upgrade ke Pro untuk menghapus watermark
    </p>
  )
}
